/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "2021.04.30-53-g48678ea8b"
#endif /* AVUTIL_FFVERSION_H */
